### ISSUE TITLE
Ctrl+CS not working on Windows

### ISSUE THREAD

**Issue by lf-araujo** [gauravk-in/cheat.sh-sublime-plugin#3]
This package is pretty stable. I have been using it on Linux and this is working pretty well, however on Windows the key combination for calling the query is not working. It still works when summoned via command palette.

**Comment by gauravk-in** [comment]
Hi, the key bindings had to be removed to add the package to Package Control. Once you update the package on Linux the key bindings should no longer work. The documentation needs to be updated. Currently the only way to use the tool is via Command Palette. 

Key bindings can be configured by users as they prefer.
